"use client";import{useEffect,useState}from"react";import{defaultSiteData,SiteData}from"../../lib/site-data";
type Item={title:string;description:string;period?:string;url?:string};
export default function Admin(){const[data,setData]=useState<SiteData>(defaultSiteData);const[loading,setLoading]=useState(true);const[status,setStatus]=useState("");const[url,setUrl]=useState("");const[preview,setPreview]=useState<any>(null);
useEffect(()=>{fetch("/api/site").then(r=>r.json()).then(setData).finally(()=>setLoading(false))},[]);
const profile=(k:keyof SiteData["profile"],v:string)=>setData(d=>({...d,profile:{...d.profile,[k]:v}}));const save=async()=>{const r=await fetch("/api/site",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});setStatus(r.ok?"Saved":"Save failed");setTimeout(()=>setStatus(""),1800)};
const inspect=async()=>{if(!url)return;const r=await fetch("/api/metadata",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url})});setPreview(await r.json())};
const addProject=()=>{setData(d=>({...d,projects:[...d.projects,{title:preview?.title||"New project",description:preview?.description||"",url}]}));setUrl("");setPreview(null)};
const add=(key:"skills"|"timeline"|"achievements"|"links")=>{const blank:any=key==="skills"? "New skill":{title:"New entry",description:"",...(key==="timeline"?{period:""}:{})};setData(d=>({...d,[key]:[...d[key],blank]} as SiteData))};
const remove=(key:any,i:number)=>setData(d=>({...d,[key]:d[key].filter((_:any,j:number)=>j!==i)}));
const update=(key:any,i:number,field:string,value:string)=>setData(d=>({...d,[key]:d[key].map((x:any,j:number)=>j===i?typeof x==="string"?value:{...x,[field]:value}:x)}));
return <main className="admin"><div className="adminHead"><div><small>UACC • MANAGEMENT</small><h1>RAJA BUNDELA</h1></div><button onClick={save} disabled={loading}>{status||"Save Changes"}</button></div><section className="adminGrid">{([["name","Name"],["tagline","Tagline"],["location","Location"],["email","Email"],["availability","Availability"]] as const).map(([k,l])=><label key={k}>{l}<input value={data.profile[k]} onChange={e=>profile(k,e.target.value)}/></label>)}</section><section className="adminSection"><h2>Projects</h2><div className="urlRow"><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="Project URL"/><button onClick={inspect}>Fetch metadata</button><button onClick={addProject}>Add</button></div>{preview&&<div className="preview"><b>{preview.title||"No title"}</b><span>{preview.description||"No description"}</span></div>}{data.projects.map((x,i)=><div className="item" key={i}><input value={x.title} onChange={e=>update("projects",i,"title",e.target.value)}/><input value={x.description} onChange={e=>update("projects",i,"description",e.target.value)}/><button onClick={()=>remove("projects",i)}>Delete</button></div>)}</section>{(["skills","timeline","achievements","links"] as const).map(key=><section className="adminSection" key={key}><h2>{key[0].toUpperCase()+key.slice(1)}</h2><button onClick={()=>add(key)}>+ Add</button>{data[key].map((x:any,i:number)=>typeof x==="string"?<div className="item" key={i}><input value={x} onChange={e=>update(key,i,"",e.target.value)}/><button onClick={()=>remove(key,i)}>Delete</button></div>:<div className="item" key={i}><input value={x.title} placeholder="Title" onChange={e=>update(key,i,"title",e.target.value)}/>{key==="timeline"&&<input value={x.period||""} placeholder="Period" onChange={e=>update(key,i,"period",e.target.value)}/>}<input value={x.description} placeholder="Description" onChange={e=>update(key,i,"description",e.target.value)}/>{key==="links"&&<input value={x.url||""} placeholder="URL" onChange={e=>update(key,i,"url",e.target.value)}/>}<button onClick={()=>remove(key,i)}>Delete</button></div>)}</section>)}</main>}