"use client";
import{useEffect,useState}from"react";
import RayonePanel from"../../components/RayonePanel";
import{defaultSiteData,SiteData}from"../../lib/site-data";

const nav=[["about","About"],["skills","Skills"],["work","Work"],["timeline","Timeline"],["achievements","Achievements"],["links","Links"],["rayone","RAYONE"],["contact","Contact"]];

export default function SectionPage({params}:{params:{section:string}}){
 const[data,setData]=useState<SiteData>(defaultSiteData),[menu,setMenu]=useState(false),[loading,setLoading]=useState(true),[contactStatus,setContactStatus]=useState("");
 useEffect(()=>{fetch("/api/site",{cache:"no-store"}).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(x=>x&&setData(x)).catch(()=>{}).finally(()=>setLoading(false))},[]);
 const p=data.profile,id=params.section.toLowerCase(),title=nav.find(x=>x[0]===id)?.[1]||"Page";
 const submitContact=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setContactStatus("Sending…");const form=e.currentTarget,fd=new FormData(form);try{const r=await fetch("/api/contact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:fd.get("name"),email:fd.get("email"),message:fd.get("message")})}),j=await r.json();if(!r.ok)throw new Error();setContactStatus("Message ready — opening your email app.");window.location.href=j.mailto+"?subject="+encodeURIComponent("Website contact from "+String(fd.get("name")||""))+"&body="+encodeURIComponent(String(fd.get("message")||"")+"\n\nReply to: "+String(fd.get("email")||""));form.reset()}catch{setContactStatus("Could not prepare the message. Please email "+p.email+" directly.")}};
 let content:React.ReactNode=<p className="muted">Page not found.</p>;
 if(id==="about")content=<><p className="sectionLead">A focused digital home for work, development, AI experiments and creative projects.</p><div className="card profileInfo"><p><strong>Name</strong><br/>{p.name}</p><p><strong>Identity</strong><br/>{p.tagline}</p><p><strong>Location</strong><br/>{p.location}</p><p><strong>Availability</strong><br/>{p.availability}</p></div></>;
 if(id==="skills")content=loading?<p className="muted">Loading…</p>:data.skills.length?<div className="grid">{data.skills.map(s=><div className="card" key={s}>{s}</div>)}</div>:<p className="muted">Skills will appear here when published.</p>;
 if(id==="work")content=loading?<p className="muted">Loading…</p>:data.projects.length?<div className="grid">{data.projects.map(x=><article className="card" key={x.title}><h3>{x.title}</h3><p>{x.description}</p>{x.url&&<a href={x.url} target="_blank" rel="noreferrer">Open project ↗</a>}</article>)}</div>:<p className="muted">Projects will appear here when published.</p>;
 if(id==="timeline")content=loading?<p className="muted">Loading…</p>:data.timeline.length?<div className="grid">{data.timeline.map(x=><article className="card" key={x.title+x.period}><small>{x.period}</small><h3>{x.title}</h3><p>{x.description}</p></article>)}</div>:<p className="muted">Timeline entries will appear here when published.</p>;
 if(id==="achievements")content=loading?<p className="muted">Loading…</p>:data.achievements.length?<div className="grid">{data.achievements.map(x=><article className="card" key={x.title}><h3>{x.title}</h3><p>{x.description}</p></article>)}</div>:<p className="muted">Achievements will appear here when published.</p>;
 if(id==="links")content=loading?<p className="muted">Loading…</p>:data.links.length?<div className="grid">{data.links.map(x=><a className="card" key={x.url} href={x.url} target="_blank" rel="noreferrer"><h3>{x.label}</h3><p>{x.url}</p></a>)}</div>:<p className="muted">Links will appear here when published.</p>;
 if(id==="rayone")content=<><p className="sectionLead">AI assistant with voice interaction and unlimited custom particle shapes.</p><RayonePanel/></>;
 if(id==="contact")content=<><p className="sectionLead">{p.email}</p><form className="contactForm" onSubmit={submitContact}><input name="name" required placeholder="Your name"/><input name="email" required type="email" placeholder="Your email"/><textarea name="message" required rows={6} placeholder="Your message"/><button className="btn primary" type="submit">Open Email</button>{contactStatus&&<p className="rayoneStatus" role="status">{contactStatus}</p>}</form></>;
 return <main className={id==="rayone"?"site rayonePage":"site"}><header className="header"><nav className="nav"><a className="brand" href="/">RAJA <span>BUNDELA</span></a><button className="menuBtn" aria-label="Toggle menu" aria-expanded={menu} onClick={()=>setMenu(v=>!v)}>☰</button><div className={"navlinks"+(menu?" open":"")}>{nav.map(([key,label])=><a key={key} href={"/"+key} onClick={()=>setMenu(false)}>{label}</a>)}</div></nav></header><section className={"section pageSection"+(id==="rayone"?" rayoneSection":"")}><h1 className="pageTitle">{title}</h1>{content}</section><footer className="footer">© {new Date().getFullYear()} {p.name}</footer></main>;
}