"use client";
import{forwardRef,useEffect,useImperativeHandle,useRef}from"react";
import*as THREE from"three";

export type RayoneHandle={
 setState:(s:"idle"|"listening"|"thinking"|"speaking")=>void;
 setShape:(nameOrText:string|number)=>void;
 customShape:(parts:any[],name?:string)=>void;
 pulse:()=>void;
 setLevel:(v:number)=>void;
 listen:()=>Promise<void>;
 speak:(text:string)=>void;
 handleText:(text:string)=>Promise<void>;
};

type Props={state?:string;shape?:string;level?:number;onReply?:(t:string)=>void;onTranscript?:(t:string)=>void;onStatus?:(t:string)=>void;onShape?:(n:string)=>void};

const RayoneNative=forwardRef<RayoneHandle,Props>(function RayoneNative({state="idle",shape="sphere",level=0,onReply,onTranscript,onStatus,onShape},ref){
 const host=useRef<HTMLDivElement>(null),stateRef=useRef(state),levelRef=useRef(level),targetRef=useRef(shape),apiRef=useRef<RayoneHandle|null>(null);
 useEffect(()=>{stateRef.current=state},[state]);useEffect(()=>{levelRef.current=level},[level]);
 useImperativeHandle(ref,()=>({setState:s=>apiRef.current?.setState(s),setShape:x=>apiRef.current?.setShape(x),customShape:(parts,name)=>apiRef.current?.customShape(parts,name),pulse:()=>apiRef.current?.pulse(),setLevel:v=>apiRef.current?.setLevel(v),listen:async()=>{await apiRef.current?.listen()},speak:text=>apiRef.current?.speak(text),handleText:async text=>{await apiRef.current?.handleText(text)} }),[]);

 useEffect(()=>{
  const el=host.current;if(!el)return;
  const slow=(navigator.hardwareConcurrency||4)<=4||innerWidth<700,N=slow?15000:34000;
  const renderer=new THREE.WebGLRenderer({antialias:false,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.setClearColor(0x050607,0);renderer.domElement.style.width="100%";renderer.domElement.style.height="100%";renderer.domElement.style.display="block";renderer.domElement.style.pointerEvents="none";el.appendChild(renderer.domElement);
  const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(55,1,.1,50),R=Math.random,g=()=> (R()+R()+R()-1.5)*.5;
  const rv=()=>{const u=R()*2-1,a=R()*Math.PI*2,q=Math.sqrt(1-u*u);return[Math.cos(a)*q,u,Math.sin(a)*q]};
  function human(){const r=R();if(r<.72){const a=R()*Math.PI*2,b=R()*2-1,rad=Math.sqrt(1-b*b),rx=.54,ry=.66,rz=.48;return[rx*rad*Math.cos(a)+g()*.018,.58+ry*b+g()*.018,rz*rad*Math.sin(a)+g()*.018]}if(r<.79){const side=R()<.5?-1:1,a=R()*Math.PI*2,rad=Math.sqrt(R())*.11;return[side*.205+Math.cos(a)*rad,.69+Math.sin(a)*rad,.47+g()*.018]}if(r<.84){const a=R()*Math.PI*2,rad=Math.sqrt(R())*.045;return[Math.cos(a)*rad,.52+Math.sin(a)*rad,.545+g()*.012]}if(r<.89){const a=R()*Math.PI*2,rad=Math.sqrt(R())*.115;return[Math.cos(a)*rad,.35+Math.sin(a)*rad,.515+g()*.012]}if(r<.95){const a=R()*Math.PI*2,rad=Math.sqrt(R())*.21;return[.02+Math.cos(a)*rad,-.42+Math.sin(a)*rad,.06+g()*.02]}const side=R()<.5?-1:1,arm=R();return[side*(.58+arm*.34)+g()*.025,-.48-arm*.42+g()*.025,.02+g()*.12]}
  const fns=[()=>{const d=rv(),k=1.5+g()*.08;return[d[0]*k,d[1]*k,d[2]*k]},()=>{const t=R()*Math.PI*2,m=1.1+.35*Math.cos(3*t);return[m*Math.cos(2*t)*1.1+g()*.12,.7*Math.sin(3*t)+g()*.12,m*Math.sin(2*t)*1.1+g()*.12]},human,()=>{const t=R()*Math.PI*2,k=Math.pow(R(),.35)*.095;return[16*Math.pow(Math.sin(t),3)*k,(13*Math.cos(t)-5*Math.cos(2*t)-2*Math.cos(3*t)-Math.cos(4*t))*k-.05,g()*.9*Math.pow(R(),.3)]},()=>{const t=(R()*2-1)*3,s=R()<.5?0:Math.PI,r=.9;return R()<.12?(()=>{const f=1-2*R();return[Math.cos(t*2)*r*f,t*.5,Math.sin(t*2)*r*f]})():[Math.cos(t*2+s)*r+g()*.08,t*.5,Math.sin(t*2+s)*r+g()*.08]}];
  const A=fns.map(f=>{const a=new Float32Array(N*3);for(let i=0;i<N;i++){const p=f();a[i*3]=p[0];a[i*3+1]=p[1];a[i*3+2]=p[2]}let cx=0,cy=0,cz=0;for(let i=0;i<N;i++){cx+=a[i*3];cy+=a[i*3+1];cz+=a[i*3+2]}cx/=N;cy/=N;cz/=N;let ex=.01;for(let i=0;i<N;i++){a[i*3]-=cx;a[i*3+1]-=cy;a[i*3+2]-=cz;ex=Math.max(ex,Math.abs(a[i*3]),Math.abs(a[i*3+1]),Math.abs(a[i*3+2]))}const s=1.6/ex;for(let i=0;i<N*3;i++)a[i]*=s;return a});A.push(new Float32Array(N*3),new Float32Array(N*3),new Float32Array(N*3));
  const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,Number(v)||0)),V=(a:any)=>[clamp(a?.[0],-3,3),clamp(a?.[1],-3,3),clamp(a?.[2],-3,3)];
  const custom=(parts:any[],name="custom")=>{const slot=targetSlot===5?6:5;parts=Array.isArray(parts)?parts.slice(0,24):[];const norm=parts.map(o=>({t:o.t,p:V(o.p),q:V(o.q||o.p),d:[clamp(o.d?.[0],.02,3),clamp(o.d?.[1],.02,3),clamp(o.d?.[2],.02,3)],w:clamp(o.w==null?1:o.w,.05,10)})).filter(o=>["s","e","c","b","r","k"].includes(o.t));if(!norm.length)return;let total=0;const weights=norm.map(o=>total+=o.w),out=A[slot];for(let i=0;i<N;i++){const rr=R()*total;let k=0;while(weights[k]<rr&&k<norm.length-1)k++;const o=norm[k],p=o.p,d=o.d;let x=0,y=0,z=0;if(o.t==="s"){const v=rv();x=p[0]+v[0]*d[0];y=p[1]+v[1]*d[0];z=p[2]+v[2]*d[0]}else if(o.t==="e"){const v=rv();x=p[0]+v[0]*d[0];y=p[1]+v[1]*d[1];z=p[2]+v[2]*d[2]}else if(o.t==="c"){const q=o.q,ax=[q[0]-p[0],q[1]-p[1],q[2]-p[2]],L=Math.hypot(...ax)||1,a=ax.map((v:number)=>v/L),v=rv(),dt=v[0]*a[0]+v[1]*a[1]+v[2]*a[2],pw=[v[0]-dt*a[0],v[1]-dt*a[1],v[2]-dt*a[2]],wl=Math.hypot(...pw)||1,u=R();x=p[0]+ax[0]*u+pw[0]/wl*d[0];y=p[1]+ax[1]*u+pw[1]/wl*d[0];z=p[2]+ax[2]*u+pw[2]/wl*d[0]}else if(o.t==="b"){const f=(R()*3)|0,u=[(R()*2-1)*d[0],(R()*2-1)*d[1],(R()*2-1)*d[2]];u[f]=(R()<.5?-1:1)*d[f];x=p[0]+u[0];y=p[1]+u[1];z=p[2]+u[2]}else if(o.t==="r"){const u=R()*Math.PI*2,v=R()*Math.PI*2,rr=d[0]+d[1]*Math.cos(v);x=p[0]+rr*Math.cos(u);y=p[1]+rr*Math.sin(u);z=p[2]+d[1]*Math.sin(v)}else{const u=R()*Math.PI*2,q=R(),rr=(1-q)*d[0];x=p[0]+Math.cos(u)*rr;y=p[1]+q*d[1];z=p[2]+Math.sin(u)*rr}out[i*3]=x+g()*.03;out[i*3+1]=y+g()*.03;out[i*3+2]=z+g()*.03}let mx=0,my=0,mz=0,ex=.01;for(let i=0;i<N;i++){mx+=out[i*3];my+=out[i*3+1];mz+=out[i*3+2]}mx/=N;my/=N;mz/=N;for(let i=0;i<N;i++){out[i*3]-=mx;out[i*3+1]-=my;out[i*3+2]-=mz;ex=Math.max(ex,Math.abs(out[i*3]),Math.abs(out[i*3+1]),Math.abs(out[i*3+2]))}const scale=1.6/ex;for(let i=0;i<N*3;i++)out[i]*=scale;targetSlot=slot;targetName=name||"custom";selectedSlot=slot;targetRef.current=targetName;geo.attributes.aTo.array.set(A[slot]);geo.attributes.aTo.needsUpdate=true;morph=0;onShape?.(targetName)};
  const geo=new THREE.BufferGeometry();geo.setAttribute("position",new THREE.BufferAttribute(A[0].slice(),3));geo.setAttribute("aTo",new THREE.BufferAttribute(A[1].slice(),3));
  const mat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,uniforms:{uMix:{value:0},uTime:{value:0},uAmp:{value:1},uBr:{value:0},uMouth:{value:0},uHuman:{value:0},uSize:{value:(slow?20:24)*renderer.getPixelRatio()}},vertexShader:`attribute vec3 aTo;uniform float uMix,uTime,uAmp,uBr,uMouth,uHuman,uSize;varying float vD;varying vec3 vC;void main(){vec3 p=mix(position,aTo,uMix);float w=sin(uMix*3.14159);float n=sin(p.x*2.+uTime)+sin(p.y*2.3+uTime*1.2)+sin(p.z*1.9+uTime*.8);float na=mix(1.,.35,uHuman);p+=normalize(p+.001)*n*.035*uAmp*na+vec3(sin(p.y*3.+uTime),sin(p.z*3.+uTime),sin(p.x*3.+uTime))*(.02*na+w*.35);float mo=uMouth*uHuman*step(abs(p.x),.24)*step(abs(p.y-.25),.07)*step(.3,p.z);p.y+=mo*(p.y>.25?.1:-.1);p*=1.+uBr;vec4 mv=modelViewMatrix*vec4(p,1.);gl_Position=projectionMatrix*mv;gl_PointSize=uSize/-mv.z;vD=smoothstep(-2.,2.,p.z);vC=mix(vec3(.05,.85,1.),vec3(.6,.3,1.),smoothstep(-1.6,1.6,p.y+sin(uTime*.5+p.x)*.4));}`,fragmentShader:`varying float vD;varying vec3 vC;void main(){float d=length(gl_PointCoord-.5);if(d>.5)discard;float a=pow(1.-d*2.,2.);gl_FragColor=vec4(vC*(.5+1.1*vD),a*.55);}`});
  const pts=new THREE.Points(geo,mat);scene.add(pts);let currentSlot=7,targetSlot=7,selectedSlot=2,morph=-1,targetName="human",env=0,rot=0,ry=0,rz=0,amp=1,spin=.15,hum=0,mouth=0,last=performance.now(),t=0,raf=0;
  const names=["sphere","knot","human","heart","dna"],kw=[["sphere","ball","gola","गोला","normal","default","wapas","वापस"],["knot","quantum","गांठ"],["human","insan","insaan","इंसानी","इंसान","इन्सान","मानव","manav","aadmi","आदमी","person","face","chehra","चेहरा","bust","woman","man"],["heart","dil","दिल","love"],["dna","helix","डीएनए"]];
  const detect=(x:string)=>{const ws=String(x).toLowerCase().split(/[^\p{L}\p{M}]+/u);for(let i=kw.length-1;i>=0;i--)if(ws.some(w=>kw[i].includes(w)||(i===2&&(w.startsWith("insa")||w.startsWith("human")))))return i;return -1};
  const setShape=(x:string|number)=>{const i=typeof x==="number"?x:detect(x);if(i<0||i>=names.length)return;targetRef.current=names[i];selectedSlot=i;if(stateRef.current==="idle")return;if(i===currentSlot&&morph<0)return;targetSlot=i;geo.attributes.aTo.array.set(A[i]);geo.attributes.aTo.needsUpdate=true;morph=0};
  const resize=()=>{const w=el.clientWidth||innerWidth,h=el.clientHeight||500;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();camera.position.z=9;pts.position.set(0,0,0);pts.scale.set(1,1,1);const halfH=Math.tan(THREE.MathUtils.degToRad(camera.fov/2))*(camera.position.z-1.5),halfW=halfH*(w/h),spread=A[7];for(let i=0;i<N;i++){spread[i*3]=(R()*2-1)*halfW*.96;spread[i*3+1]=(R()*2-1)*halfH*.94;spread[i*3+2]=(R()*2-1)*1.3}if(currentSlot===7&&morph<0){geo.attributes.position.array.set(spread);geo.attributes.position.needsUpdate=true}if(stateRef.current==="idle"&&targetSlot===7){geo.attributes.aTo.array.set(spread);geo.attributes.aTo.needsUpdate=true}};resize();addEventListener("resize",resize);
  const speak=async(text:string)=>{if(typeof speechSynthesis==="undefined"){stateRef.current="idle";return}stateRef.current="speaking";const u=new SpeechSynthesisUtterance(text);u.lang=/[\u0900-\u097F]/.test(text)?"hi-IN":"en-IN";u.onstart=()=>{stateRef.current="speaking"};u.onboundary=()=>{env=1};u.onend=()=>{stateRef.current="idle"};speechSynthesis.cancel();speechSynthesis.speak(u)};
  const ask=async(messages:any[])=>{const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages})});if(!r.ok)throw new Error("http "+r.status);const j=await r.json();return j.reply||""};
  const sys="You are RAYONE, a concise, warm AI assistant. Reply in the same language the user writes in (Hinglish/Hindi/English), max 3 short sentences.";
  const shapeSys='Convert the request into a 3D point-cloud object. Reply ONLY JSON: {"name":"short english name","parts":[{"t":"s","p":[x,y,z],"d":[r],"w":1}]}. Types: s sphere, e ellipsoid, c cylinder/limb p-to-q, b box, r torus, k cone. y is up, object faces +z, fit -1.5..1.5, use 8-20 parts, weights .05-10. If not an object reply {"name":"none","parts":[]}';
  const handleText=async(text:string)=>{const q=text.trim();if(!q)return;stateRef.current="thinking";const k=detect(q);try{if(k>=0){setShape(k);const reply=await ask([{role:"system",content:sys},{role:"user",content:q}]);onReply?.(reply);await speak(reply);return}if(/(bana|banao|bano|dikha|show|make|become|turn into|shape|form|draw|create|बना|बनो|दिखा|आकार)/i.test(q)){const raw=await ask([{role:"user",content:shapeSys+"\nRequest: "+q}]);const parsed=JSON.parse(raw.slice(raw.indexOf("{"),raw.lastIndexOf("}")+1));if(parsed?.parts?.length){custom(parsed.parts,parsed.name||"custom");onStatus?.("Shape तैयार है");await speak("यह रहा "+(parsed.name||"आपका आकार"));return}}if(k<0&&selectedSlot!==7){targetSlot=selectedSlot;geo.attributes.aTo.array.set(A[selectedSlot]);geo.attributes.aTo.needsUpdate=true;morph=0}const reply=await ask([{role:"system",content:sys},{role:"user",content:q}]);onReply?.(reply);await speak(reply)}catch{onStatus?.("RAYONE अभी उपलब्ध नहीं है।");stateRef.current="idle"}};
  let stream:MediaStream|null=null,ctx:AudioContext|null=null,rec:any=null;
  const stopMic=()=>{stream?.getTracks().forEach(t=>t.stop());stream=null;ctx?.close();ctx=null};
  const listen=async()=>{const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){onStatus?.("इस browser में voice recognition support नहीं है");return}if(rec){rec.stop();return}try{stream=await navigator.mediaDevices.getUserMedia({audio:true});ctx=new AudioContext();const an=ctx.createAnalyser();an.fftSize=256;ctx.createMediaStreamSource(stream).connect(an);const d=new Uint8Array(an.frequencyBinCount);const tick=()=>{if(!stream)return;an.getByteFrequencyData(d);let s=0;for(const v of d)s+=v;levelRef.current=Math.min(1,s/d.length/60);requestAnimationFrame(tick)};tick();rec=new SR();rec.lang="hi-IN";rec.interimResults=true;let heard="";rec.onstart=()=>{stateRef.current="listening"};rec.onresult=(e:any)=>{heard=Array.from(e.results).map((x:any)=>x[0].transcript).join("");onTranscript?.(heard);setShape(heard)};rec.onerror=()=>{};rec.onend=()=>{stopMic();rec=null;levelRef.current=0;if(heard.trim())handleText(heard);else stateRef.current="idle"};rec.start()}catch{stopMic();onStatus?.("Microphone permission नहीं मिली");stateRef.current="idle"}};
  apiRef.current={setState:s=>{stateRef.current=s},setShape,customShape:custom,pulse:()=>{env=1},setLevel:v=>{levelRef.current=Math.max(0,Math.min(1,v))},listen,speak,handleText};
  const loop=(now:number)=>{const dt=Math.min((now-last)/1000,.05);last=now;t+=dt;const U=mat.uniforms;U.uTime.value=t;const L=stateRef.current==="listening"?levelRef.current:0;env*=.92;const sp=stateRef.current==="speaking"?Math.min(1,env+.25*Math.abs(Math.sin(t*9))):0;const ta=stateRef.current==="speaking"?1.2+sp*3:stateRef.current==="thinking"?1.8:stateRef.current==="listening"?1.2+L*4:1,ts=stateRef.current==="thinking"?1.1:stateRef.current==="speaking"?.45:stateRef.current==="listening"?.25:.15;amp+=(ta-amp)*.12;spin+=(ts-spin)*.05;rot+=spin*dt;U.uAmp.value=amp;U.uBr.value=stateRef.current==="speaking"?.02+.1*sp:stateRef.current==="listening"?.02+.12*L:stateRef.current==="thinking"?-.06+.03*Math.sin(t*9):.02*Math.sin(t*1.5);mouth+=(sp-mouth)*.4;U.uMouth.value=mouth;hum+=((currentSlot===2&&morph<0?1:0)-hum)*.1;if(morph>=0){morph+=dt/1.4;const m=Math.min(morph,1);U.uMix.value=m*m*(3-2*m);if(morph>=1){geo.attributes.position.array.set(A[targetSlot]);geo.attributes.position.needsUpdate=true;U.uMix.value=0;currentSlot=targetSlot;morph=-1}}const targetIndex=stateRef.current==="idle"?7:(targetSlot===5||targetSlot===6?targetSlot:names.indexOf(targetRef.current));if(targetIndex>=0&&targetIndex!==currentSlot&&morph<0){targetSlot=targetIndex;geo.attributes.aTo.array.set(A[targetIndex]);geo.attributes.aTo.needsUpdate=true;morph=0}const hv=currentSlot===2;ry+=(hv?Math.sin(t*.6)*.3:rot-ry)*.08;rz+=((hv&&stateRef.current==="listening"?.12:0)-rz)*.06;pts.rotation.y=ry;pts.rotation.z=rz;pts.rotation.x=Math.sin(t*.3)*.15+(hv?.05*sp*Math.sin(t*8):0);renderer.render(scene,camera);raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);
  return()=>{cancelAnimationFrame(raf);removeEventListener("resize",resize);stopMic();renderer.dispose();geo.dispose();mat.dispose();el.removeChild(renderer.domElement)};
 },[]);
 return <div ref={host} style={{position:"fixed",inset:0,width:"100vw",height:"100vh",pointerEvents:"none",zIndex:0}} aria-label="RAYONE AI particle core"/>;
});
export default RayoneNative;